#!/usr/bin/env bash
# Claude Code Companion — local-mode setup script
# Sets up the .env file and verifies dependencies.

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; }
section() { echo -e "\n${BOLD}$*${NC}"; }

# ── Check dependencies ────────────────────────────────────────────────────────
section "Checking dependencies..."

if ! command -v claude &>/dev/null; then
    error "'claude' command not found."
    echo "  Install Claude Code: https://docs.anthropic.com/en/docs/claude-code"
    exit 1
fi
CLAUDE_VER=$(claude --version 2>/dev/null || echo "unknown")
info "Claude Code found: $CLAUDE_VER"

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
    error "Python 3 not found. Please install Python 3.10+."
    exit 1
fi
PYTHON=$(command -v python3 || command -v python)
PY_VER=$($PYTHON --version 2>&1)
info "Python found: $PY_VER"

# ── Collect credentials ───────────────────────────────────────────────────────
section "Configuration"

echo ""
echo "You need two things:"
echo "  1. A Telegram bot token  — create one with @BotFather"
echo "  2. Your Telegram user ID — get it from @userinfobot"
echo ""

read -rp "Telegram bot token: " TELEGRAM_TOKEN
if [[ -z "$TELEGRAM_TOKEN" ]]; then
    error "Bot token cannot be empty."
    exit 1
fi

read -rp "Your Telegram user ID: " TELEGRAM_USER_ID
if [[ ! "$TELEGRAM_USER_ID" =~ ^[0-9]+$ ]]; then
    error "User ID must be a number."
    exit 1
fi

# ── Optional settings ─────────────────────────────────────────────────────────
echo ""
read -rp "Default working directory [~]: " INITIAL_DIR
INITIAL_DIR="${INITIAL_DIR:-~}"

read -rp "Restrict Claude Code to project directory? (y/N): " RESTRICT_PATHS_INPUT
if [[ "${RESTRICT_PATHS_INPUT,,}" == "y" ]]; then
    RESTRICT_PATHS="true"
else
    RESTRICT_PATHS="false"
fi

# ── Write .env ────────────────────────────────────────────────────────────────
section "Writing .env..."

ENV_FILE="$(dirname "$0")/.env"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh
TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
INITIAL_DIR=${INITIAL_DIR}
RESTRICT_PATHS=${RESTRICT_PATHS}
EOF

info ".env written to $ENV_FILE"

# ── Install Python dependencies ───────────────────────────────────────────────
section "Installing Python dependencies..."

REQUIREMENTS="$(dirname "$0")/requirements.txt"
if [[ ! -f "$REQUIREMENTS" ]]; then
    error "requirements.txt not found at $REQUIREMENTS"
    exit 1
fi

if $PYTHON -m pip install -r "$REQUIREMENTS" --quiet; then
    info "Dependencies installed."
else
    error "pip install failed. Try: pip install -r requirements.txt"
    exit 1
fi

# ── Done ──────────────────────────────────────────────────────────────────────
section "Setup complete!"
echo ""
echo "  Start the bot with:"
echo -e "    ${BOLD}python bot.py${NC}"
echo ""
echo "  Then open Telegram, find your bot, and send /start"
echo ""
warn "Make sure 'claude auth login' has been run and Claude Code is authenticated."
